[package]
name = "graphql"
version = "0.1.0"
edition = "2024"

[dependencies]
async-graphql = "7.0.15"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.140"
sycamore = { version = "0.9.1", features = ["serde"] }
web-sys = { version = "0.3.77", features = ["Storage"] }
